import type { InfoContent } from "./InfoButton"

const COPY: Record<string, string> = {
  "Stress": "Body activation during still minutes, from 0 to 3. Movement, workouts and sleep are excluded.",
  "Hours of sleep": "Time asleep during your main sleep session, excluding awake periods.",
  "Skin temp (from baseline)": "Nightly temperature difference from your personal baseline, not your absolute body temperature.",
  "Stress Monitor": "Body activation from 0 to 3, based on heart rate during still minutes. Movement, workouts and sleep are excluded.",
  "Health Monitor": "Your nightly vital signs compared with your personal baseline. Unusual readings are signals to watch, not diagnoses.",
  "Healthspan": "Pulse Age combines fitness, sleep and strain patterns to estimate how your habits relate to long-term health.",
  "Fitness": "Your estimated aerobic fitness and training load, based on the measurements available from Google Health.",
  "Heart rate": "Heartbeats per minute recorded throughout the day. Gaps mean no reading was available.",
  "Heart rate variability": "Variation in time between heartbeats during sleep, in milliseconds. Compare it with your own usual range.",
  "Resting heart rate": "Your heart rate at rest. Pulse uses sleeping heart rate when a daily resting value is unavailable.",
  "Respiratory rate": "Breaths per minute during sleep, measured by your Fitbit.",
  "Blood oxygen": "Estimated oxygen saturation during sleep, measured by your Fitbit. Compare changes with your usual readings.",
  "Skin temperature": "Nightly temperature difference from your personal baseline, not your absolute body temperature.",
  "Sleep performance": "How your sleep compares with your personal need, adjusted for consistency, efficiency and restorative sleep.",
  "Recovery": "Your readiness for the day, based on overnight measurements and your recent baseline.",
  "Strain": "Daily cardiovascular effort on a scale from 0 to 21. Workouts and everyday activity both contribute.",
  "Calories": "Estimated energy burned for the day or activity shown.",
  "Steps": "Steps counted through the day. Today's count builds as new activity syncs.",
  "Weight": "Your latest weight from a connected scale or a manual log.",
  "Body fat": "Body fat percentage from a smart scale or a manual log.",
  "Distance": "Distance covered during the day or activity shown.",
  "Floors": "Floors climbed, counted from changes in altitude while walking.",
  "Elevation gain": "Total height gained during the day.",
  "Active minutes": "Minutes recorded as moderate or vigorous physical activity.",
  "Light activity": "Minutes of light physical activity recorded through the day.",
  "Active Zone Minutes": "Activity minutes weighted by intensity. Higher-intensity minutes can count more than once.",
  "Active calories": "Energy burned through movement, excluding resting energy.",
  "Sedentary time": "Minutes recorded as sedentary during the day.",
  "Average heart rate": "Average of the heart rate readings during the day or activity shown.",
  "Water": "Water logged for the day. This reflects entries, not measured hydration.",
  "Calories eaten": "Energy from food logged for the day. Missing entries make the total incomplete.",
  "Protein": "Protein in the food logged for the day, in grams.",
  "Carbohydrates": "Carbohydrates in the food logged for the day, in grams.",
  "Fat": "Fat in the food logged for the day, in grams.",
  "Blood glucose": "Your latest blood glucose reading from a connected meter or a manual log.",
  "Core temperature": "Logged body temperature readings in degrees Celsius.",
  "Swim strokes": "Total swim strokes recorded in the day's activities.",
  "Recovery trend": "Daily recovery scores over the selected period. Missing scores remain gaps.",
  "What shaped it": "The overnight measurements that contributed to this day's recovery, compared with your baseline.",
  "Tomorrow’s forecast": "An estimate based on your recent recovery and today's strain. Your next overnight measurements can change it.",
  "Time in zones": "Recorded minutes grouped by heart rate zone. Higher zones represent greater cardiovascular effort.",
  "Activities": "Activities imported from your connected source for the selected day.",
  "Last night’s sleep": "Your main sleep session compared with your previous 30 days.",
  "Hours vs. needed": "Sleep obtained compared with your personal baseline sleep need.",
  "Sleep consistency": "How regularly your sleep and wake times occur across recent nights.",
  "Restorative sleep": "Time spent in deep and REM sleep, the stages grouped here as restorative sleep.",
  "Sleep efficiency": "Time asleep as a percentage of the main sleep session's duration.",
  "Sleep debt": "Recent sleep shortfall carried forward into your estimated sleep need.",
  "Pace of Aging": "How recent habits compare with the patterns used to estimate Pulse Age. Short-term changes can be noisy.",
  "Pulse Age history": "Changes in your estimated Pulse Age over time. This is a model estimate, not a clinical measurement.",
  "Percentile": "How your estimated aerobic fitness compares with the reference population for your profile.",
  "VO2 max trend": "Estimated aerobic capacity over time. It reflects the VO2 max measurements available from your source.",
  "Training load": "Recent training effort compared with your longer-term load, showing how quickly workload is changing.",
  "Fitness, fatigue and form": "Fitness reflects longer-term load, fatigue reflects recent load, and form is the balance between them.",
  "Recovery breakdown": "Number of days in each recovery range during the report period.",
  "Averages": "Averages use days with recorded values. Missing days are excluded rather than counted as zero.",
  "Training balance": "How strain and recovery lined up during the report period.",
  "Top journal effects": "Associations between logged habits and your scores. These comparisons do not prove a habit caused a change.",
  "Best and worst day": "The highest and lowest recovery days with available scores in this period.",
  "History": "Recorded values over the selected range. Gaps mean data was unavailable, not zero.",
  "By weekday": "Average recorded values grouped by weekday across the available period.",
  "Minutes by intensity": "Activity time split into the intensity levels reported by your source.",
  "Workouts": "Recorded workouts contributing to this day's activity.",
  "Logged entries": "Individual entries available for the selected day. Daily totals depend on what was logged.",
  "Eaten vs. burned": "Logged food energy compared with estimated energy burned. Missing food entries can make intake look low.",
  "Macros": "Protein, carbohydrates and fat from the day's logged food.",
  "Readings": "Individual measurements available on or before the selected day.",
  "Unusual days": "Recorded values outside your recent personal range. An unusual value is not a diagnosis.",
  "Movement by hour": "Hourly steps show when movement was recorded. A gap does not prove you were sedentary.",
  "Steps by hour": "Steps recorded in each hour of the selected day.",
  "This week": "Recorded activity for the week containing the selected day. Missing days remain incomplete.",
  "Last 7 days": "Summary of recorded values in the last 7 days, compared with the 7 days before.",
  "Last 30 days": "Summary of recorded values in the last 30 days, compared with the 30 days before.",
  "Last 6 months": "Summary of recorded values in the last 6 months, compared with the 6 months before.",
  "Last 12 months": "Summary of recorded values in the last year, compared with the year before.",
}

export function cardInfo(title: string): InfoContent | undefined {
  const body = COPY[title]
  return body ? { title, body } : undefined
}
